### ISSUE TITLE
Deprecate C loader, revisit 32blit docs

### ISSUE THREAD

**Issue by Gadgetoid** [32blit/32blit-sdk#395]
As of #393 we have canonicalised on the 32blit Python toolset for all builds/flashes. This doesn't mean the C tool can't still be maintained/used, but it should be deprecated from the view of this repository so the docs aren't confusing.

We should drop or mark with a deprecation warning the associated docs - https://github.com/pimoroni/32blit-beta/blob/master/docs/32Blit-Loader.md

Also potentially need to revisit https://github.com/pimoroni/32blit-beta/blob/master/docs/32blit.md but a quick glance doesn't reveal anything too eggregious.

I suspect separating the 32blit C flasher out of this repository into its own home might be a good idea.

**Comment by Daft-Freak** [comment]
C tool has moved out now and 32Blit-Loader.md is gone.

**Comment by Gadgetoid** [comment]
Thank you!
