### ISSUE TITLE
Can’t build for 32Blit on all Platforms

### ISSUE THREAD

**Issue by lummi01** [32blit/32blit-sdk#848]
The new created .blit files are corrupted for the 32Blit Console.
Tested on Win10, Win11, Linux Mint and Raspberry OS.
Local builds are ok.

**Comment by Daft-Freak** [comment]
https://github.com/32blit/32blit-tools/pull/103 should help. `pip install bitstring==4.0.0` may also be a workaround (assuming bitstring was installed through pip with the tools).

I haven't (yet) found anything other than images to be broken. I've only checked a few examples and picovision-3d though.

**Comment by lummi01** [comment]
'bitstring==4.0.0' fix the problem with the splash screen but the .blit file is still corrupted.
Even the pure 32Blit-Boilerplate without any changes produce this failure.
![IMG_4360](https://github.com/32blit/32blit-sdk/assets/72337143/9eaea32a-e101-45d0-896c-df526ac1bcb6)

**Comment by Daft-Freak** [comment]
Hmm, I think the most likely cause of that error message is an incompatible firmware version... and I may have bumped the API version since the last release. So if you're using the latest SDK git you'll need to build/install the firmware.

(Not surprising that I forgot that my device wasn't running released firmware...)

**Comment by lummi01** [comment]
That was exactly the problem. Sorry for my ignorance...

**Comment by Daft-Freak** [comment]
Well, it's not the most helpful error message.

I should really finish https://github.com/32blit/32blit-sdk/pull/822 so it can be more specific. :thinking: 

(... and maybe do something crazy like make a release that has PicoVision support)

**Comment by Gadgetoid** [comment]
> (... and maybe do something crazy like make a release that has PicoVision support)

:eyes:

**Comment by Daft-Freak** [comment]
Splashes should be fixed with latest release of the tools and the launcher should be more clear about version incompatibility in the future.

Plus there isn't an unreleased API bump any more.
